SOURCES := $(shell ls *.cpp) glad.c
HEADERS := $(shell ls *.h)
OBJECTS := $(foreach i, $(SOURCES), $(i).o)
LIBS := -lglfw -lGL -lX11 -lpthread -lXrandr -lXi -ldl -lbox2d
CFLAGS := -ggdb2

.PHONY: default
default: main

%.c.o:%.c
	@echo CC $<
	@gcc -c $< -o $@ $(CFLAGS)

%.cpp.o:%.cpp
	@echo CPP $<
	@g++ -c $< -o $@ $(CFLAGS)

main: $(OBJECTS)
	@echo LINK main
	@g++ $(OBJECTS) -o main $(LIBS) $(CFLAGS)

.PHONY: run
run: main
	@./main

.PHONY: clean
clean:
	@rm $(OBJECTS) main -rf